# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20170606_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='todolist.Tag'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='tasklist',
        ),
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ManyToManyField(related_name='tasks', to='todolist.Tasklist'),
        ),
    ]
