# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20170606_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasklist',
        ),
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.Tasklist'),
            preserve_default=False,
        ),
    ]
